name: List Playwright Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  list-tests:
#    if: github.event.pull_request.merged == true  # Run only if PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: List Playwright tests in JSON format
        run: |
          echo "Generating Playwright test list in JSON format..."
          npx playwright test --list --reporter=json > playwright-tests.json
          cat playwright-tests.json  # Show JSON output in GitHub Actions log

      - name: Upload JSON test list as artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-list
          path: playwright-tests.json

      - name: Create GitHub Release and Upload JSON
        uses: softprops/action-gh-release@v2
        with:
          files: playwright-tests.json
          tag_name: "playwright-tests-${{ github.run_number }}"
          release_name: "Playwright Test List - Run #${{ github.run_number }}"
          body: "Playwright test list generated for this run."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}