name: List Playwright Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  list-tests:
#    if: github.event.pull_request.merged == true  # Run only if PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Find Playwright tests and log them
        run: |
          echo "Listing all Playwright tests in the project:"
          npx playwright test --list | tee playwright-tests.log

      - name: Upload test list as artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-list
          path: playwright-tests.log