name: "Run Playwright Tests on Demand"

on:
  workflow_dispatch:

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

       #  (Optional) If your tests require Playwright browsers each run:
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Clean Allure reports
        run: rm -rf allure-results allure-report

      - name: Run Playwright tests
        run: npx playwright test



      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
